version: "3"
services:
  web:
    image: stehrn/get-started:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /Users/nikstehr/IdeaProjects/docker/data:/data
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet: